### ISSUE TITLE
Pico-Go status bar is visible in non-pico projects

### ISSUE THREAD

**Issue by timstrasser** [Drincann/Pico-Go#2]
## What are the steps to reproduce this issue?
1. Install extension
2. Open any folder in VSCode

## What happens?
The Pico-Go status bar appears, no matter if the current folder is a Pico project or not.

## What were you expecting to happen?
I would expect the Pico-Go extension, to be loaded only if I'm inside a Pico project.

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

## Support info

Copy this from the `Pico-Go > Help > Get support info` option in the command palette:

```
Get support info" does not print anything into console.
```

**Comment by soup-bowl** [comment]
Even if there's not a uniform way of being able to detect whether the current active folder is a Pico project, it would be good if the statusbar module condenses when it has no actions (e.g. hide the upload/download/reset options). Otherwise on smaller screens the huge statusbar takes up a lot of screen estate.

Amazing plugin though - another contributed step to having to avoid having an IDE dedicated to the Pico/Arduinos.

**Comment by paulober** [comment]
Fixed this in Pico-W-Go
